# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
    args: ['--unsafe']
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.3
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
    - id: codespell
      args: [--write-changes, --ignore-words=.codespell-ignore]
      additional_dependencies:
        - tomli
      exclude: '^pdm\.lock$'

# Ensure GitHub Actions workflows are valid
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.1
  hooks:
    - id: actionlint
